### ISSUE TITLE
Error when trying to build corpus

### ISSUE THREAD

**Issue by eldams** [cblavier/twitter-feelings#1]
Hi Christian,

I am very interested in building a corpus for a sentiment analysis evaluation campaign (https://deft.limsi.fr/2015/). Unfortunately, when I tried to run:

```
./twitter_feelings build-corpus --lang fr --mood positive
```

It did complain 

```
Could not start application redis_pool: RedisPool.start(:normal, []) returned an error: shutdown: failed to start child: :tf_pool
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:connection_error, {:connection_error, :econnrefused}}}
            src/poolboy.erl:260: :poolboy.new_worker/1
            src/poolboy.erl:281: :poolboy.prepopulate/3
            src/poolboy.erl:143: :poolboy.init/3
            (stdlib) gen_server.erl:306: :gen_server.init_it/6
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

Any hint? I am new to erlang so I have absolutely no idea where to start... help appreciated indeed!

**Comment by cblavier** [comment]
It looks like it cannot connect to your Redis database.
Make sure you have Redis installed and running and run the script again!

**Comment by eldams** [comment]
Hi Christian,

You were partly right :) In fact redis was installed but not started. This may ba a Mac OS issue.
Maybe could you add this info to your README for Mac users, start redis with:
    redis-server &

Also, it looks like redis has to be started _before_ running mix deps.
It now works like a charm, if I use the resulting a corpus I'll make a reference to your software.

Best,

Damien

PS: et je parle en anglais sur github, mais aussi, tout de même, en français "merci pour ce logiciel" :)

**Comment by cblavier** [comment]
Super, merci du retour !
